apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ibm-event-automation
  namespace: openshift-gitops
spec:
  sourceRepos:
    - 'https://github.com/paind-hs25/paind.v0.0.git'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
