apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-event-streams-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "101"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: ibm-event-automation
  source:
    repoURL: 'https://github.com/paind-hs25/paind.v0.0.git'
    path: components/operators/eventstreams
    targetRevision: main

  syncPolicy:
    automated:
      prune: true
      selfHeal: true