apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  name: mq
  namespace: ibm-mq
spec:
  license:
    accept: true
    license: L-CYPF-CRPF3H
    use: Production
  queueManager:
    availability:
      type: SingleInstance
    metrics:
      enabled: true
      tls:
        provider: openshift
    name: CUSTOM
    storage:
      defaultClass: ocs-external-storagecluster-ceph-rbd #block
      queueManager:
        type: persistent-claim
  version: 9.4.3.0-r1
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
