apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-eventendpointmanagement
  labels:
    backup.events.ibm.com/component: subscription        
spec:
  channel: v11.6
  name: ibm-eventendpointmanagement
  source: ibm-eventendpointmanagement-catalog
  sourceNamespace: openshift-marketplace