apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-eventstreams
  labels:
    backup.eventstreams.ibm.com/component: subscription        
spec:
  channel: v12.0
  name: ibm-eventstreams
  source: ibm-eventstreams
  sourceNamespace: openshift-marketplace