resources: 
#- apiconnect.yaml
#- appconnect.yaml
#- aspera.yaml
#- datapower-gateway.yaml
#- eventautomation-flink.yaml
#- eventendpointmanagement.yaml
#- eventprocessing.yaml
#- eventstreams.yaml
- foundational-services.yaml
#- integration-asset-repository.yaml
#- cp4i.yaml
#- mq.yaml
#- redis.yaml