apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: gateway-1
  labels:
    backup.events.ibm.com/component: eventgateway
  namespace: ibm-event-automation
spec:
  license:
    accept: true
    license: L-CYPF-CRPF3H
    metric: VIRTUAL_PROCESSOR_CORE
    use: CloudPakForIntegrationProduction
  managerEndpoint: >- # adjust to your environment
    https://event-manager-instance-ibm-eem-gateway-ibm-event-automation.apps.itz-qs5sfj.hub03-lb.techzone.ibm.com 
  maxNumKafkaBrokers: 20
  gatewayGroupName: gateway-group
  gatewayID: gateway-1
  tls:
    caSecretName: event-manager-instance-ibm-eem-manager-ca
