apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-eventprocessing
spec:
  channel: v1.4
  name: ibm-eventprocessing
  source: ibm-eventprocessing-catalog
  sourceNamespace: openshift-marketplace