apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-flink-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ibm-event-automation
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/paind-hs25/paind.v0.0.git'
    path: components/instances/ibm-apache-flink
    targetRevision: main

  syncPolicy:
    automated:
      prune: true
      selfHeal: true