kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ibm-flink-pvc
  namespace: ibm-event-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-external-storagecluster-cephfs #file
