apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: eventstreams
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
  namespace: ibm-event-automation
spec:
  version: latest
  license:
    accept: true
    license: L-CYPF-CRPF3H
    use: CloudPakForIntegrationProduction
  adminApi: {}
  adminUI:
    authentication:
      - type: integrationKeycloak
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  strimziOverrides:
    kafka:
      authorization:
        type: simple
      config:
        log.cleaner.threads: 6
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
        default.replication.factor: 3
        min.insync.replicas: 2
        auto.create.topics.enable: 'false'
      listeners:
        - name: external
          port: 9094
          type: route
          tls: true
          authentication:
            type: scram-sha-512
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: prod-3-brokers-metrics-config
    nodePools:
      - name: kafka
        replicas: 3
        storage:
          type: persistent-claim
          size: 2Gi
          class: ocs-external-storagecluster-ceph-rbd # adjust based on environment
        roles:
          - broker
        resources:
          requests:
            memory: 8096Mi
            cpu: 2000m
          limits:
            memory: 8096Mi
            cpu: 2000m
      - name: controller
        replicas: 3
        storage:
          type: persistent-claim
          size: 4Gi
          class: ocs-external-storagecluster-ceph-rbd # adjust based on environment
        roles:
          - controller
