apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-operator-group
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "150"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  project: cert-manager
  source:
    repoURL: 'https://github.com/paind-hs25/paind.v0.0.git'
    path: components/operatorGroups/cert-manager
    targetRevision: main

  syncPolicy:
    automated:
      prune: true
      selfHeal: true